[package]
name = "proj-lite-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
proj-lite = { path = ".." }
geo-traits = { version = "0.3.0", default-features = false }
wasm-bindgen = "0.2.100"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
