[package]
name = "proj-lite-sys"
version = "0.1.0"
edition = "2024"
links = "proj"

[dependencies]
libsqlite3-sys = { version = "0.35", features = ["bundled"] }
link-cplusplus = "1.0"

[build-dependencies]
cmake = "0.1"
flate2 = "1.1"
tar = "0.4"
